teleop_node:
  ros__parameters:
    axis_linear:
      x: 0
    scale_linear:
      x: -8.5 
    scale_linear_turbo:
      x: -3.5

    axis_angular:
      yaw: 1
    scale_angular:
      yaw: -8.5
    scale_angular_turbo:
      yaw: -1.5


    enable_button: 6
    enable_turbo_button: 7

    require_enable_button: true